# Generated by Django 2.1.7 on 2019-04-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('photo_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g2.Film')),
            ],
        ),
    ]
