# Generated by Django 2.1.7 on 2019-04-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g2', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-timestamp',)},
        ),
    ]
